package codes

type CODE string

const (
	NOT_FOUND     CODE = "NOT_FOUND"
	TEAM_EXISTS   CODE = "TEAM_EXISTS"
	PR_EXISTS     CODE = "PR_EXISTS"
	INVALID_INPUT CODE = "INVALID_INPUT"
	PR_MERGED     CODE = "PR_MERGED"
	NOT_ASSIGNED  CODE = "NOT_ASSIGNED"
	NO_CANDIDATE  CODE = "NO_CANDIDATE"
)
