POST http://localhost:8080/team/add

{
  "team_name": "backend-2",
  "members": [
    {
      "user_id": "u1",
      "username": "Alice",
      "is_active": true
    },
    {
      "user_id": "u2",
      "username": "Notan",
      "is_active": true
    },
    {
      "user_id": "u3",
      "username": "Bob",
      "is_active": true
    },
    {
      "user_id": "u4",
      "username": "Alex",
      "is_active": false
    }
  ]
}

HTTP/1.1 201  - Created
content-type: application/json; charset=utf-8
date: Sun, 16 Nov 2025 14:39:38 GMT
content-length: 256
connection: close
###
GET http://localhost:8080/team/get?team_name=backend-2

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
date: Sun, 16 Nov 2025 14:39:42 GMT
content-length: 247
connection: close
###
POST http://localhost:8080/users/setIsActive
Admin-Token:admin

{
    "user_id": "u4",
    "team_name": "backend-2",
    "is_active": true
}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
date: Sun, 16 Nov 2025 14:40:02 GMT
content-length: 84
connection: close
###
GET http://localhost:8080/users/getReview?user_id=u4&team_name=backend-2

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
date: Sun, 16 Nov 2025 14:40:07 GMT
content-length: 35
connection: close
###
POST http://localhost:8080/pullRequest/create

{
  "pull_request_id": "pr-7",
  "pull_request_name": "Add search",
  "author_id": "u4",
  "team_name": "backend-2"
}

HTTP/1.1 404  - Not Found
content-type: application/json; charset=utf-8
date: Sun, 16 Nov 2025 14:39:24 GMT
content-length: 61
connection: close
###
POST http://localhost:8080/pullRequest/merge

{
  "pull_request_id": "pr-6"
}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
date: Sun, 16 Nov 2025 13:42:02 GMT
content-length: 203
connection: close
###
POST http://localhost:8080/pullRequest/reassign

{
  "pull_request_id": "pr-7",
  "old_reviewer_id": "u3"
}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
date: Sun, 16 Nov 2025 14:14:55 GMT
content-length: 175
connection: close